name: Publish NuGet Package

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"  # Triggers when a tag like v1.0.0 is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build the project
        run: dotnet build R.NET.sln --configuration Release

      - name: Pack the NuGet package
        run: dotnet pack R.NET.sln --configuration Release --output ./artifacts

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "./artifacts/rdotnet2*" --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json"
